//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long ID { get; set; }
        public string FunctionName { get; set; }
        public string InputData { get; set; }
        public string OutputData { get; set; }
        public Nullable<System.DateTime> RowCreatedOn { get; set; }
    }
}
