//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpText
    {
        public int Id { get; set; }
        public string HelpTextKey { get; set; }
        public string HelpTextValue { get; set; }
    }
}
